language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
env: blah=TRUE

addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp tconf.js pconfig.js